"""
Fuses predictions from multiple models using Weighted Box Fusion (WBF), NMS, or Soft-NMS.

Reads JSONL prediction files from each model's output directory and generates
a single combined predictions JSONL dataset, then automatically evaluates it 
(mAP and FROC) if the split is 'val' or 'test'. Outputs are organized by split.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from scripts.config import EnsembleConfig, HardwarePreset, get_output_root, get_processed_data_root
from scripts.predict_logger import stack_predictions, evaluate_predictions, evaluate_froc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fuse predictions from multiple models")
    
    # Model prediction flags
    parser.add_argument(
        "--yolo-pred",
        type=str,
        help="Path to YOLO predictions JSONL (e.g., outputs/yolo/predictions_val.jsonl)",
    )
    parser.add_argument(
        "--frcnn-pred",
        type=str,
        help="Path to Faster R-CNN predictions JSONL (e.g., outputs/faster_rcnn/predictions_val.jsonl)",
    )
    parser.add_argument(
        "--detr-pred",
        type=str,
        help="Path to DETR predictions JSONL (e.g., outputs/detr/predictions_val.jsonl)",
    )
    
    # Split handling
    parser.add_argument(
        "--split",
        type=str,
        required=True,
        choices=["train", "val", "test"],
        help="Split these predictions belong to (determines output folder and evaluation).",
    )
    
    # Weight configuration
    parser.add_argument(
        "--weights",
        nargs="+",
        type=float,
        default=None,
        help="Manual weights for each provided model, in the order: YOLO, Faster R-CNN, DETR. "
             "Skip weight for any model not provided.",
    )
    parser.add_argument(
        "--tuned-weights",
        type=str,
        default=None,
        help="Path to a tuned_weights.json file generated by tune_weights.py. "
             "Overrides --weights if provided.",
    )
    
    # Ensemble parameters
    parser.add_argument(
        "--ensemble-method",
        type=str,
        default="wbf",
        choices=["wbf", "nms", "soft_nms"],
        help="Fusion method to use.",
    )
    parser.add_argument(
        "--ensemble-iou",
        type=float,
        default=0.5,
        help="IoU threshold for ensemble fusion.",
    )
    parser.add_argument(
        "--ensemble-skip",
        type=float,
        default=0.05,
        help="skip_box_thr for ensemble fusion (boxes below this score are dropped before fusion).",
    )
    parser.add_argument(
        "--normalize-scores",
        action="store_true",
        help="Apply Min-Max scaling to the scores of each model before fusion.",
    )
    
    # Evaluation parameters
    parser.add_argument(
        "--preset",
        type=str,
        default="medium",
        choices=["small", "medium", "large"],
        help="Preset size to load data config mapping (for resolving image sizes during evaluation).",
    )
    parser.add_argument(
        "--score-thr", 
        type=float, 
        default=0.0,
        help="Filter fused boxes with score < threshold before evaluation."
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # 1. Collect inputs and maintain strict ordering for weights
    model_preds = []
    model_names = []
    
    if args.yolo_pred:
        model_preds.append(args.yolo_pred)
        model_names.append("yolo")
    if args.frcnn_pred:
        model_preds.append(args.frcnn_pred)
        model_names.append("frcnn")
    if args.detr_pred:
        model_preds.append(args.detr_pred)
        model_names.append("detr")
        
    if not model_preds:
        print("Error: At least one model prediction file must be provided "
              "(--yolo-pred, --frcnn-pred, or --detr-pred).")
        sys.exit(1)

    # 2. Resolve weights
    weights = None
    if args.tuned_weights:
        print(f"Loading tuned weights from {args.tuned_weights}...")
        with open(args.tuned_weights, "r") as f:
            tuned_data = json.load(f)
        
        # Extract weights matching the provided models
        weights = []
        for name in model_names:
            if name in tuned_data["weights"]:
                weights.append(tuned_data["weights"][name])
            else:
                print(f"Error: Model '{name}' not found in tuned weights.")
                sys.exit(1)
                
    elif args.weights:
        weights = args.weights
        if len(weights) != len(model_preds):
            print(f"Error: Provided {len(weights)} weights, but {len(model_preds)} models were specified.")
            sys.exit(1)

    # 3. Configure Ensemble
    ensemble_cfg = EnsembleConfig(
        iou_thr=args.ensemble_iou,
        skip_box_thr=args.ensemble_skip,
        method=args.ensemble_method,
    )
    
    output_dir = Path(get_output_root()) / "ensemble" / args.split
    output_dir.mkdir(parents=True, exist_ok=True)

    # Auto-detect WBF sub-type for distinct output filenames
    wbf_variant = "default"
    if args.ensemble_method == "wbf":
        if args.normalize_scores:
            wbf_variant = "normalized"
        elif weights and not all(w == weights[0] for w in weights):
            # Non-equal manual weights → "skew" variant
            wbf_variant = "skew"

    # Build filename with variant suffix to avoid overwrites
    if args.ensemble_method == "wbf" and wbf_variant != "default":
        fused_path = output_dir / f"fused_predictions_wbf_{wbf_variant}.jsonl"
    else:
        fused_path = output_dir / f"fused_predictions_{args.ensemble_method}.jsonl"
    
    print(f"\n--- Stacking Models ({args.split} split) ---")
    print(f"Models: {', '.join(model_names)}")
    print(f"Method: {args.ensemble_method} (IoU={args.ensemble_iou}, Skip={args.ensemble_skip})")
    if weights:
        print(f"Weights: {weights}")
    
    # 4. Run Fusion
    stack_predictions(
        pred_files=model_preds,
        output_path=fused_path,
        cfg=ensemble_cfg,
        weights=weights,
        normalize=args.normalize_scores,
    )
    print(f"Fused predictions saved to → {fused_path}")

    # 5. Evaluate (if possible)
    preset_cfg = {
        "small": HardwarePreset.small,
        "medium": HardwarePreset.medium,
        "large": HardwarePreset.large,
    }[args.preset](arch="yolo")  # Arch doesn't matter here, just need DataConfig
    data_cfg = preset_cfg.data
    
    prepared_dataset_root = Path(get_processed_data_root())
    if not (prepared_dataset_root / "dataset.yaml").exists():
        prepared_dataset_root = None

    print(f"\nEvaluating fused predictions on {args.split} split...")
    try:
        metrics = evaluate_predictions(
            fused_path,
            data_cfg,
            split=args.split,
            prepared_dataset_root=prepared_dataset_root,
        )

        display_names = {
            "map": "mAP@50-95",
            "map_50": "mAP@50",
            "map_75": "mAP@75",
        }
        print("\n  === Results ===")
        for k, v in metrics.items():
            label = display_names.get(k, k)
            if isinstance(v, float):
                print(f"  {label}: {v:.4f}")
            else:
                print(f"  {label}: {v}")

        # --- FROC evaluation ---
        print(f"\n  Computing FROC score on {args.split} split...")
        froc_result = evaluate_froc(
            fused_path,
            data_cfg,
            split=args.split,
            prepared_dataset_root=prepared_dataset_root,
        )

        print(f"\n  === FROC Results (IoU={froc_result['iou_threshold']}) ===")
        print(f"  FROC Score: {froc_result['froc_score']:.4f}")
        print(
            f"  GT Lesions: {froc_result['total_gt_lesions']}  |  Images: {froc_result['total_images']}"
        )
        for rate, sens in zip(froc_result["fp_rates"], froc_result["sensitivities"]):
            print(f"    Sensitivity @ {rate} FP/img: {sens:.4f}")

        # Merge FROC into metrics
        metrics["froc_score"] = froc_result["froc_score"]
        metrics["froc_sensitivities"] = froc_result["sensitivities"]
        metrics["froc_fp_rates"] = froc_result["fp_rates"]
        metrics["froc_iou_threshold"] = froc_result["iou_threshold"]

        # Save metrics to JSON
        metrics_path = fused_path.with_suffix(".metrics.json")
        serializable = {}
        for k, v in metrics.items():
            if isinstance(v, float):
                serializable[k] = round(v, 6)
            elif isinstance(v, (int, str, bool, list)):
                serializable[k] = v
            else:
                serializable[k] = str(v)
        
        serializable["split"] = args.split
        serializable["models"] = model_names
        serializable["weights"] = weights if weights else [1.0] * len(model_names)
        serializable["ensemble_method"] = args.ensemble_method
        serializable["normalize_scores"] = args.normalize_scores
        serializable["wbf_variant"] = wbf_variant
        serializable["score_threshold"] = args.score_thr

        with open(metrics_path, "w") as f:
            json.dump(serializable, f, indent=2)
        print(f"\n  Metrics saved to {metrics_path}")

    except Exception as e:
        print(f"Evaluation failed: {e}")


if __name__ == "__main__":
    main()
